### ISSUE TITLE
linter-yalafi overwrites the default server option of YaLafi

### ISSUE THREAD

**Issue by torik42** [mfbehrens99/linter-yalafi#22]
Currently, the option `--lt-server` is passed to YaLafi. Default value is 'lt' which means that even if you configured YaLafi to use a local server, linter-yalafi will use the online service.

**Comment by mfbehrens99** [comment]
I would say that this behaviour is intended. If this was "fixed" then one would not be able to sometimes use the public LT server without removing all local server configurations

**Comment by torik42** [comment]
Couldn’t this be done as with #14? We just add a default option which does not add `--lt-server=lt` at all.

**Comment by mfbehrens99** [comment]
I think this is not a good idea. Since LaTeX is used by many people that are not developers I think it is important that it should be easy to set up. I think it is already difficult for somebody not involved in developing to install the `yalafi` module. I really don't want people to be forced by default to install an LT-server on their computer. For all the people who know LT and potentially have their own LT servers set up it is very easy and also easy to understand how to change the setting. Even if they would not change the setting it would still be working with the public LT server.

I hope you understand this reason. I know that you want to parse as few arguments to YaLafi by default as possible, and I totally agree with you on that. But I really want to help all those people who are just getting started or only want their LaTeX files to be checked.

**Comment by mfbehrens99** [comment]
As far as I know, yes.

Can I close this issue?

**Comment by torik42** [comment]
Yes. We start parallel discussions again. I will comment in #20.
