### ISSUE TITLE
Add `--simple-equations` to command by default

### ISSUE THREAD

**Issue by mfbehrens99** [mfbehrens99/linter-yalafi#9]
`--simple-equations` is a YaLafi options that just ignores equations. That removed all my problems with false positives in equations. I think it would be good if this could be enabled by default

**Comment by torik42** [comment]
I suggest not to make this a default option. But we can add it nevertheless.

I added an option to add arbitrary YaLafi arguments in #6.

**Comment by mfbehrens99** [comment]
Why are you against using it as default?

**Comment by torik42** [comment]
I would try to avoid passing options to YaLafi by default that are not already default options of YaLafi (as e.g. with the `WHITESPACE_RULE`). Then, if you already used YaLafi also linter-yalafi works as you expect. If a user has even defined a YaLafi config file, passing a default argument will overwrite it, I guess. That would also be a good reason to not pass the `WHITESPACE_RULE`.

In this particular case I even like false positives if there is an option to disable them. Otherwise, beginners would maybe never know that YaLafi can detect mistakes inside equations.

**Comment by torik42** [comment]
If I understand #14 correctly, this issue can be closed.
